# Running the vectorization

This notebook can be used to test functions or run the entire process of vectorizing. Please also keep in mind that when you run this it may overwrite existing files, so please watch out for that.

In [6]:
from run_vectorization import main

main()

Loading dataset...
Creating TF-IDF vectorizer...
Vectorizing reviews...
Saving outputs...
Vectorization complete.
Samples: 121
Features: 3000

In [ ]:
import pandas as pd

# Please change the path if needed, currently it is structured to how the github repo is organized, but if you run
# this locally in visual studio, you might need to change the path.
data_X = pd.read_csv("Advanced-Programming_Final-Project/switch2_vectorization/data/X_features.csv")
data_y = pd.read_csv("Advanced-Programming_Final-Project/switch2_vectorization/data/y_scores.csv")

In [ ]:
# Display the first few rows, in total there are 121 rows, one for each review.
data_X.head()

,10,10 10,10 minutes,100,1080p,11,12,120fps,13,15,...,za,zelda,zelda games,zelda notes,zero,zombies,zonai,zone,zones,zoom
0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.000000,0.0,0.0,0.000000,0.0,0.0,0.02433,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.063014,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.014046,0.0,0.0,0.014882,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [ ]:
# The scores, not really special, but still good to show.
data_y.head()

   score
0      8
1      9
2      7
3      8
4      8